export const ADD_QUESTIONS_STARTED = "ADD_QUESTIONS_STARTED";
export const SET_RANDOM_QUESTIONS = "SET_RANDOM_QUESTIONS";
export const FETCH_QUIZ_DATA_COMPLETE = "FETCH_QUIZ_DATA_COMPLETE";
export const FETCH_QUIZ_DATA_ERROR = "FETCH_QUIZ_DATA_ERROR";
